import { useCallback, useEffect, useRef, useState } from 'react';
import axios from 'axios';

export interface AssetPlacement { id:string; type:'MDF'|'IDF'|'WAREHOUSE'; canonical_code:string; name:string; status:string; active:boolean }
interface AuthorizedBranch { id:string; name:string; city:string; selected:boolean }

interface Props { assetType:string; value:string; onChange:(id:string, placement?:AssetPlacement)=>void; onBranchChange?:(branchID:string)=>void }

export default function AssetPlacementSelector({assetType,value,onChange,onBranchChange}:Props){
  const [branches,setBranches]=useState<AuthorizedBranch[]>([]); const [branchID,setBranchID]=useState('');
  const [items,setItems]=useState<AssetPlacement[]>([]); const [loading,setLoading]=useState(true);
  const onChangeRef=useRef(onChange); const branchChangeRef=useRef(onBranchChange); const valueRef=useRef(value);
  useEffect(()=>{onChangeRef.current=onChange},[onChange]); useEffect(()=>{branchChangeRef.current=onBranchChange},[onBranchChange]); useEffect(()=>{valueRef.current=value},[value]);
  const loadPlacements=useCallback(async(selectedBranch:string)=>{if(!selectedBranch){setItems([]);return}const r=await axios.get('/api/dcim/placements');if(r.data.branch_id!==selectedBranch)throw new Error('branch context mismatch');const next:AssetPlacement[]=(r.data?.placements||[]).map((p:any)=>({...p,canonical_code:p.canonical_code||p.code}));setItems(next);if(valueRef.current){const selected=next.find(p=>p.id===valueRef.current);selected?onChangeRef.current(selected.id,selected):onChangeRef.current('')}},[]);
  const load=useCallback(async()=>{setLoading(true);try{const r=await axios.get('/api/auth/select-branch');const available:AuthorizedBranch[]=r.data?.branches||[];setBranches(available);let selected=available.find(b=>b.selected)?.id||'';if(!selected&&available.length===1){selected=available[0].id;await axios.post('/api/auth/select-branch',{branchId:selected})}setBranchID(selected);branchChangeRef.current?.(selected);await loadPlacements(selected)}finally{setLoading(false)}},[loadPlacements]);
  useEffect(()=>{void load();const focus=()=>void load();window.addEventListener('focus',focus);return()=>window.removeEventListener('focus',focus)},[load]);
  const selectBranch=async(nextBranch:string)=>{onChangeRef.current('');branchChangeRef.current?.(nextBranch);setItems([]);setBranchID(nextBranch);setLoading(true);try{await axios.post('/api/auth/select-branch',{branchId:nextBranch});setBranches(previous=>previous.map(b=>({...b,selected:b.id===nextBranch})));await loadPlacements(nextBranch)}catch{const previous=branches.find(b=>b.selected)?.id||'';setBranchID(previous);branchChangeRef.current?.(previous)}finally{setLoading(false)}};
  const createWarehouse=async()=>{const name=window.prompt('Nombre del Almacén');if(!name||!branchID)return;const r=await axios.post('/api/dcim/placements',{type:'WAREHOUSE',name});await loadPlacements(branchID);onChangeRef.current(r.data.id,{id:r.data.id,type:'WAREHOUSE',canonical_code:r.data.code,name:r.data.name,status:'active',active:true})};
  const link=(type:'MDF'|'IDF')=>`/infraestructura/mdf-idf?create=${type}&return_to=${encodeURIComponent(location.pathname)}&asset_type=${assetType}&branch_id=${branchID}`;
  return <div style={{display:'grid',gap:10}}><label><b>1. Sucursal *</b><select disabled={loading||branches.length===0} value={branchID} onChange={e=>void selectBranch(e.target.value)} style={{width:'100%',padding:10,marginTop:4}}><option value="">Seleccione sucursal</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}{b.city?` · ${b.city}`:''}</option>)}</select></label><label><b>2. Ubicación *</b><select disabled={loading||!branchID} value={value} onChange={e=>onChangeRef.current(e.target.value,items.find(p=>p.id===e.target.value))} style={{width:'100%',padding:10,marginTop:4}}><option value="">{!branchID?'Seleccione sucursal':loading?'Cargando…':'Seleccione ubicación'}</option>{items.map(p=><option key={p.id} value={p.id}>{p.type} · {p.canonical_code} · {p.name}</option>)}</select></label>{!loading&&branchID&&items.length===0&&<div style={{padding:12,background:'#fff7ed',border:'1px solid #fdba74',borderRadius:8}}>No existen ubicaciones disponibles para esta sucursal.<div style={{display:'flex',gap:8,marginTop:8}}><a href={link('MDF')} target="_blank" rel="noreferrer">+ Crear MDF</a><a href={link('IDF')} target="_blank" rel="noreferrer">+ Crear IDF</a><button type="button" onClick={createWarehouse}>+ Crear Almacén</button></div></div>}</div>
}
