import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import axios from 'axios';
import { ArrowLeft, CheckCircle, Edit2, Eye, Hash, Plus, RefreshCw, ShieldCheck, Tag } from 'lucide-react';
import AppLayout from '../../../components/AppLayout';

interface NamingRule {
  id: string; asset_type_code: string; asset_type_name: string; prefix: string; separator: string;
  include_branch: boolean; seq_digits: number;
  last_seq: number; next_code_preview: string; active: boolean; description: string;
  custom_segment_1: string; custom_segment_2: string; custom_segment_1_label: string; custom_segment_2_label: string;
}
interface CatalogType { code: string; name: string; description: string; requires_nomenclature: boolean; rule: NamingRule | null; }
interface FormState {
  description: string; prefix: string; separator: string; include_branch: boolean;
  seq_digits: number; active: boolean; custom_segment_1: string;
  custom_segment_2: string; custom_segment_1_label: string; custom_segment_2_label: string;
}

const DEFAULT_PREFIX: Record<string, string> = { MDF:'MDF', IDF:'IDF', RACK:'RK', SWITCH:'SW', PATCH_PANEL:'PP', NODE:'ND', UPS:'UPS', PDU:'PDU', BACKBONE:'BB', SERVER:'SRV', FIREWALL:'FW', CCTV:'CCTV', AC_UNIT:'AC' };
const ICONS: Record<string, string> = { SWITCH:'🔀', RACK:'🗄️', MDF:'🏢', IDF:'📦', UPS:'⚡', PDU:'🔌', SERVER:'💻', PATCH_PANEL:'🔗', BACKBONE:'🌐', CCTV:'📷', AC_UNIT:'❄️', NODE:'📡', FIREWALL:'🛡️' };
const blankForm = (code: string): FormState => ({ description:'', prefix:DEFAULT_PREFIX[code] || code.slice(0,4), separator:'-', include_branch:true, seq_digits:4, active:true, custom_segment_1:'', custom_segment_2:'', custom_segment_1_label:'Segmento 1', custom_segment_2_label:'Segmento 2' });
const formFromRule = (r: NamingRule): FormState => ({ description:r.description || '', prefix:r.prefix, separator:r.separator, include_branch:r.include_branch, seq_digits:r.seq_digits, active:r.active, custom_segment_1:r.custom_segment_1 || '', custom_segment_2:r.custom_segment_2 || '', custom_segment_1_label:r.custom_segment_1_label || 'Segmento 1', custom_segment_2_label:r.custom_segment_2_label || 'Segmento 2' });

export default function NomenclaturasPage() {
  const [catalog,setCatalog]=useState<CatalogType[]>([]); const [canManage,setCanManage]=useState(false);
  const [loading,setLoading]=useState(true); const [selected,setSelected]=useState<CatalogType|null>(null);
  const [form,setForm]=useState<FormState>(blankForm('SWITCH')); const [saving,setSaving]=useState(false);
  const [error,setError]=useState(''); const [saved,setSaved]=useState(false); const [highlightType,setHighlightType]=useState('');
  const [fromWizard,setFromWizard]=useState(false); const openedFromQuery=useRef(false); const cardRefs=useRef<Record<string,HTMLDivElement|null>>({});

  const load=useCallback(async()=>{ setLoading(true); try { const res=await axios.get('/api/dcim/catalogs/naming-rules'); setCatalog(res.data?.asset_types || []); setCanManage(Boolean(res.data?.can_manage)); setError(''); } catch { setCatalog([]); setError('No fue posible cargar el catálogo normativo.'); } finally { setLoading(false); } },[]);
  useEffect(()=>{ const p=new URLSearchParams(window.location.search); setHighlightType((p.get('type')||'').toUpperCase()); setFromWizard(p.get('from')==='wizard'); load(); },[load]);
  const openEditor=useCallback((item:CatalogType)=>{ setSelected(item); setForm(item.rule?formFromRule(item.rule):blankForm(item.code)); setError(''); setSaved(false); },[]);
  useEffect(()=>{ if(loading||!highlightType||openedFromQuery.current)return; const item=catalog.find(x=>x.code===highlightType); if(!item)return; openedFromQuery.current=true; cardRefs.current[highlightType]?.scrollIntoView({behavior:'smooth',block:'center'}); if(canManage)openEditor(item); },[loading,highlightType,catalog,canManage,openEditor]);

  const structuralLocked=Boolean(selected?.rule&&selected.rule.last_seq>0);
  const preview=useMemo(()=>{ if(!selected)return ''; const parts=[form.prefix.trim().toUpperCase()||'PREFIX']; if(form.include_branch)parts.push('BRANCH'); if(form.custom_segment_1.trim())parts.push(form.custom_segment_1.trim().toUpperCase().replace(/\s+/g,'')); if(form.custom_segment_2.trim())parts.push(form.custom_segment_2.trim().toUpperCase().replace(/\s+/g,'')); parts.push(String((selected.rule?.last_seq||0)+1).padStart(form.seq_digits,'0')); return parts.join(form.separator); },[selected,form]);

  const save=async()=>{ if(!selected||!form.prefix.trim()){setError('El prefijo es obligatorio.');return;} setSaving(true);setError(''); const payload={asset_type_code:selected.code,prefix:form.prefix.trim().toUpperCase(),separator:form.separator,include_branch:form.include_branch,seq_digits:form.seq_digits,active:form.active,description:form.description,custom_segment_1:form.custom_segment_1||null,custom_segment_2:form.custom_segment_2||null,custom_segment_1_label:form.custom_segment_1_label||'Segmento 1',custom_segment_2_label:form.custom_segment_2_label||'Segmento 2'}; try { if(selected.rule)await axios.put(`/api/dcim/catalogs/naming-rules/${selected.rule.id}`,payload); else await axios.post('/api/dcim/catalogs/naming-rules',payload); setSaved(true);setSelected(null);await load(); } catch(e:unknown){ const response=(e as {response?:{status?:number;data?:{error?:string}}}).response; if(response?.status===409&&response.data?.error==='normative_version_required')setError('Esta norma ya emitió códigos. Los cambios estructurales requieren una nueva versión normativa.'); else if(response?.status===409)setError('Este tipo ya tiene una norma configurada.'); else if(response?.status===403)setError('Solo un administrador puede modificar normas.'); else setError(response?.data?.error||'No fue posible guardar la norma.'); } finally{setSaving(false);} };
  const returnToWizard=()=>{window.close();setTimeout(()=>window.history.back(),150);};
  const input={width:'100%',padding:'9px 10px',borderRadius:7,border:'1px solid #dbe1ea',fontSize:13,boxSizing:'border-box' as const}; const label={display:'block',fontSize:12,fontWeight:700,color:'#475569',marginBottom:4};

  return <AppLayout title="Normativa de Nomenclaturas" breadcrumb={[{label:'Infraestructura'},{label:'Catálogos'},{label:'Normativa de Nomenclaturas'}]}><div style={{padding:'24px 28px',maxWidth:1120}}>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'start',gap:16,marginBottom:18}}><div><h1 style={{margin:0,fontSize:23,display:'flex',gap:9,alignItems:'center'}}><ShieldCheck color="#4361EE"/> Normativa de Nomenclaturas</h1><p style={{color:'#64748b',fontSize:13}}>Catálogo normativo de identificación técnica por tipo de activo.</p></div><div style={{display:'flex',gap:8}}>{fromWizard&&<button onClick={returnToWizard} style={{padding:'8px 13px',borderRadius:8,border:'1px solid #f59e0b',background:'#fffbeb',color:'#92400e',cursor:'pointer',display:'flex',gap:5}}><ArrowLeft size={14}/> Regresar al alta de {highlightType}</button>}<button onClick={load} style={{padding:'8px 13px',borderRadius:8,border:'1px solid #dbe1ea',background:'#fff',cursor:'pointer',display:'flex',gap:5}}><RefreshCw size={14}/> Actualizar</button></div></div>
    {highlightType&&<div style={{padding:12,borderRadius:9,background:'#fff7ed',border:'1px solid #fdba74',color:'#9a3412',marginBottom:16}}>Tipo solicitado desde el alta: <strong>{highlightType}</strong>. {canManage?'El formulario correspondiente se abrió automáticamente.':'Consulta la norma; solo un administrador puede definirla.'}</div>}
    {saved&&<div style={{padding:12,borderRadius:9,background:'#ecfdf5',color:'#047857',marginBottom:16,display:'flex',gap:6}}><CheckCircle size={15}/> Norma guardada correctamente. El wizard recargará el preview al regresar.</div>}
    {error&&!selected&&<div style={{padding:12,borderRadius:9,background:'#fef2f2',color:'#b91c1c',marginBottom:16}}>{error}</div>}
    {loading?<div style={{padding:60,textAlign:'center',color:'#94a3b8'}}>Cargando catálogo normativo…</div>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(310px,1fr))',gap:14}}>{catalog.map(item=>{const state=!item.rule?'NO CONFIGURADA':item.rule.active?'ACTIVA':'INACTIVA';const color=state==='ACTIVA'?'#047857':state==='INACTIVA'?'#b45309':'#b91c1c';return <div key={item.code} ref={el=>{cardRefs.current[item.code]=el;}} style={{background:'#fff',borderRadius:12,padding:16,border:highlightType===item.code?'2px solid #f59e0b':'1px solid #e2e8f0',boxShadow:highlightType===item.code?'0 0 0 3px #fef3c7':'none'}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div style={{display:'flex',gap:10}}><span style={{fontSize:24}}>{ICONS[item.code]||'📦'}</span><div><strong>{item.name}</strong><div style={{fontSize:11,color:'#64748b'}}>{item.code} · {item.requires_nomenclature?'Tipo administrado':'Configurable futuro'}</div></div></div><span style={{color,background:`${color}12`,padding:'3px 8px',borderRadius:20,fontSize:10,fontWeight:800,height:18}}>{state}</span></div><p style={{minHeight:34,fontSize:12,color:'#64748b'}}>{item.rule?.description||item.description||'Sin descripción normativa.'}</p><div style={{background:'#f8fafc',borderRadius:8,padding:10,display:'flex',justifyContent:'space-between'}}><div><small>Preview</small><div><Eye size={12}/> <code>{item.rule?.next_code_preview||'—'}</code></div></div><div style={{textAlign:'right'}}><small>Último consecutivo</small><div><Hash size={12}/> {item.rule?.last_seq??0}</div></div></div>{canManage&&<button onClick={()=>openEditor(item)} style={{marginTop:12,width:'100%',padding:8,borderRadius:8,border:'1px solid #c7d2fe',background:'#eef2ff',color:'#3730a3',cursor:'pointer',fontWeight:700}}>{item.rule?<><Edit2 size={13}/> Editar norma</>:<><Plus size={13}/> Definir norma</>}</button>}</div>;})}</div>}
    {selected&&<div style={{marginTop:20,padding:20,background:'#fff',border:'2px solid #4361ee',borderRadius:12}}><h2 style={{marginTop:0}}><Tag size={18}/> {selected.rule?'Editar':'Definir'} norma · {selected.code}</h2>{structuralLocked&&<div style={{padding:10,background:'#fff7ed',color:'#9a3412',borderRadius:8,marginBottom:14}}>Esta norma ya emitió códigos. La estructura está bloqueada; solo pueden cambiar descripción y estado.</div>}{error&&<div style={{padding:10,background:'#fef2f2',color:'#b91c1c',borderRadius:8,marginBottom:14}}>{error}</div>}<div style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr 1fr',gap:12}}>
      <div><label style={label}>Nombre / descripción normativa</label><input style={input} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder={`Estándar corporativo para ${selected.name}`}/></div><div><label style={label}>Prefijo</label><input disabled={structuralLocked} style={input} value={form.prefix} onChange={e=>setForm({...form,prefix:e.target.value.toUpperCase()})}/></div><div><label style={label}>Separador</label><input disabled={structuralLocked} maxLength={5} style={input} value={form.separator} onChange={e=>setForm({...form,separator:e.target.value})}/></div><div><label style={label}>Dígitos</label><select disabled={structuralLocked} style={input} value={form.seq_digits} onChange={e=>setForm({...form,seq_digits:Number(e.target.value)})}>{[2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></div>
      <div><label style={label}>Etiqueta segmento 1</label><input disabled={structuralLocked} style={input} value={form.custom_segment_1_label} onChange={e=>setForm({...form,custom_segment_1_label:e.target.value})}/></div><div><label style={label}>Valor segmento 1</label><input disabled={structuralLocked} style={input} value={form.custom_segment_1} onChange={e=>setForm({...form,custom_segment_1:e.target.value.toUpperCase()})}/></div><div><label style={label}>Etiqueta segmento 2</label><input disabled={structuralLocked} style={input} value={form.custom_segment_2_label} onChange={e=>setForm({...form,custom_segment_2_label:e.target.value})}/></div><div><label style={label}>Valor segmento 2</label><input disabled={structuralLocked} style={input} value={form.custom_segment_2} onChange={e=>setForm({...form,custom_segment_2:e.target.value.toUpperCase()})}/></div></div>
      <div style={{display:'flex',gap:16,flexWrap:'wrap',margin:'14px 0'}}><label><input disabled={structuralLocked} type="checkbox" checked={form.include_branch} onChange={e=>setForm({...form,include_branch:e.target.checked})}/> Incluir sucursal</label><label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Norma activa</label></div>
      <div style={{background:'#eef2ff',color:'#3730a3',padding:12,borderRadius:8}}><strong>Preview:</strong> <code>{preview}</code></div><div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:14}}><button onClick={()=>setSelected(null)}>Cancelar</button><button disabled={saving} onClick={save} style={{padding:'9px 18px',border:0,borderRadius:8,background:'#4361ee',color:'#fff',fontWeight:700}}>{saving?'Guardando…':'Guardar norma'}</button></div></div>}
  </div></AppLayout>;
}
